name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build-and-deploy:
        
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Set up Docker Buildx  
        uses: docker/setup-buildx-action@v2

      - name: Building Image
        run: docker build -f Dockerfile -t ${{ secrets.DOCKERHUB_USERNAME }}/gateway:v0.1 .

      - name: Pushing image on DockerHub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/gateway:v0.1
